# Project information
site_name: 'JTSDK Tools'
site_description: 'Development Frameworks, Librarys and CLI Appllications'
site_author: 'Greg Beam, KI7MT'

# Copyright
copyright: 'Copyright &copy; 2018 - 2019 Greg Beam, KI7MT'

nav:
    - Home: 'index.md'
    - Installation:
      - Windows:
        - 'Overview': 'windows/Home.md'
        - '1. NetCore': 'windows/Install-Net-Core-SDK.md'
        - '2. VS Code': 'windows/Install-VS-Code.md'
        - '3. Git Client': 'windows/Install-Git-Client.md'
        - '4. Core Tools': 'windows/Install-Core-Tools.md'
        - '5. Python': 'windows/Install-Python.md'
        - '6. AsciiDoctor': 'windows/Install-Asciidoctor.md'
        - '7. Qt Tools': 'windows/Install-Qt.md'
        - '8. Core Apps': 'windows/Install-Core-Apps.md'
        - '9. MSYS2': 'windows/Install-Msys2.md'
        - 'Third Party Installers': 'windows/Third-Party-Installers.md'
        - 'Version Matrix': 'windows/Version-Matrix.md'        
        - Optional Installs:
          - 'Database Tools': 'windows/Install-DB-Tools.md'
          - 'Doc Tools': 'windows/Install-Doc-Tools.md'
          - 'Java Tools': 'windows/Install-Java-Tools.md'
          - 'Java': 'windows/Install-Java.md'
          - 'PostgreSQL': 'windows/Install-PostgreSQL.md'
          - 'Redis': 'windows/Install-Redis.md'
          - 'WSL': 'windows/Install-WSL.md'
          - 'Misc Tools': 'windows/Install-Misc-Tools.md'
          - 'Eclipse': 'windows/Install-Eclipse.md'
          - 'MSSQL': 'windows/Install-MSSQL-Server.md'
          - 'MongoDB': 'windows/Install-MongoDB.md'
          - 'MSSQL': 'windows/Install-MSSQL-Server.md'
          - 'Visual Stuidio': 'windows/Install-Visual-Studio.md'
        - Release Notes:
          - 'Overview': 'windows/release-notes/Home.md'          
          - '3.0.4': 'windows/release-notes/Release-Notes-3.0.4.md'
          - '3.0.3': 'windows/release-notes/Release-Notes-3.0.3.md'
          - '3.0.2': 'windows/release-notes/Release-Notes-3.0.2.md'
          - '3.0.1': 'windows/release-notes/Release-Notes-3.0.1.md'
        - Upgrades:
          - 'Overview': 'windows/upgrades/Home.md'
          - '3.0.4': 'windows/upgrades/Upgrade-3.0.4.md'
          - '3.0.3': 'windows/upgrades/Upgrade-3.0.3.md'
          - '3.0.2': 'windows/upgrades/Upgrade-3.0.2.md'
          - '3.0.1': 'windows/upgrades/Upgrade-3.0.1.md'
          - 'PostgreSQL-10.6': 'windows/upgrades/Postgresql-10.6.md'        
    - Tools:
      - 'Overview': 'tools/cli-tools-overview.md'
      - 'jtenv': 'tools/jtenv.md'
      - 'jtconfig': 'tools/jtconfig.md'
      - 'jtbuildcm': 'tools/jtbuildcm.md'
      - Bets Testing:
        - 'jtenvjv': 'tools/jtenvjv.md'
        - 'jtenvpy': 'tools/jtenvpy.md'
        - 'wsprcsv': 'tools/wsprcsv.md'
        - 'atcheck': 'tools/atcheck.md' 
        - 'NetCore Global Tools': 'tools/global-tools-overview.md'
    - User Gude:
      - 'User Guide': 'user-guide/User-Guide.md'    
# Configuration
theme:
  name: 'flatly'
  language: 'en'

# Extensions
markdown_extensions:
  - toc:
        permalink: true
